### ISSUE TITLE
PerceiverResampler missing some LayerNorms?

### ISSUE THREAD

**Issue by inspirit** [lucidrains/flamingo-pytorch#1]
Hey, it feels like PerceiverResampler is missing some LayerNorms?
it seems to me we should layer-norm `x` before sending to attentions loop, and may be add layer-norm to `ff(latents) + latents`?

**Comment by lucidrains** [comment]
Indeed I'll add it soon

Lol, just finished building it

**Comment by lucidrains** [comment]
@inspirit all done :) https://github.com/lucidrains/flamingo-pytorch/releases/tag/0.0.6

**Comment by lucidrains** [comment]
layernorm for feedforward is here https://github.com/lucidrains/flamingo-pytorch/blob/main/flamingo_pytorch/flamingo_pytorch.py#L14

**Comment by lucidrains** [comment]
@inspirit hmm, that's the way Perceiver IO had it, and I figured with Oriol on their team, they would use the exact same architecture https://github.com/lucidrains/perceiver-pytorch/blob/main/perceiver_pytorch/perceiver_io.py#L33

**Comment by lucidrains** [comment]
@inspirit but you are right, if the media comes from the output of the final layernorm in the transformer (or otherwise), then it is redundant 🤔  i'll make it an option some time next week :)

**Comment by inspirit** [comment]
I am talking about `x` here:
https://github.com/lucidrains/flamingo-pytorch/blob/932d2a0997b436d7c6c91d29c92d989d4fb80000/flamingo_pytorch/flamingo_pytorch.py#L104

you pass it later to different attention layers without it being modified so its probably make sense to simply norm it once
after adding `time_pos_emb`
