### ISSUE TITLE
zeroing out attention not working

### ISSUE THREAD

**Issue by dhansmair** [lucidrains/flamingo-pytorch#10]
https://github.com/lucidrains/flamingo-pytorch/blob/749f8244794002371913d2fc4e7411afd5eddc67/flamingo_pytorch/flamingo_pytorch.py#L179

you are not using the inplace version of the function: https://pytorch.org/docs/stable/generated/torch.Tensor.masked_fill_.html#torch.Tensor.masked_fill_

so I think this line does not have an effect.

Best, David

**Comment by lucidrains** [comment]
@dhansmair thank you for catching this! https://github.com/lucidrains/flamingo-pytorch/commit/10913abbc8b2ceabb2320560d7d9b85fcb85eee3

**Comment by dhansmair** [comment]
sure thing!
