### ISSUE TITLE
Missing flatten op in PerceiverResampler? 

### ISSUE THREAD

**Issue by zengyan-97** [lucidrains/flamingo-pytorch#8]
Hi, 
It seems that Flamingo did 
"x_f = flatten(x_f) # [T, S, d] -> [T * S, d]" 
(batch size == 1) before putting x_f to attention. 

So, it should be like: 
medias = torch.randn(1, 2, 256, 1024) # (batch, time, sequence length, dimension)
perceived = perceive(medias) # (1, 64, 1024) - (batch, num latents, dimension)

??

**Comment by lucidrains** [comment]
@zengyan-97 Hi Yan

I don't think this is correct, since they maintain causality during the cross attention later on. Each piece of text can only attend to the last media item in the past

**Comment by zengyan-97** [comment]
Hi Phil, 
Thanks for your reply! 
I think these are two different things, video encoding and cross attention. 
For video multimodal data, I guess the input could be like (video_clip1, text1, video_clip2, text2, ...). 

Figure 4 in Flamingo paper gives the code, there is a flatten op: 

x_f, # The [T, S, d] visual features (T=time, S=space)
# Add the time position embeddings and flatten. 
x_f = x_f + time_embeddings 
x_f = flatten(x_f) # [T, S, d] -> [T * S, d]
# Apply the Perceiver Resampler layers. 


On the other hand, 64 for each video frame in resampling is too much... Swin-base outputs only 49 tokens for each 224x224 image input.

**Comment by zengyan-97** [comment]
Update: Figure 7 in Flamingo paper shows the examples of their training datasets. They just used video-text pairs.

**Comment by lucidrains** [comment]
@zengyan-97 ohh hey, yes, you are correct

sorry, i think i confused the time dimension with the number of medias dimension

this repository currently only supports same sized images for the media

do you have a need to work with video?

**Comment by lucidrains** [comment]
@zengyan-97 for video you would flatten the time and sequence (presumably add some time positional encoding just before that operation)

**Comment by lucidrains** [comment]
@zengyan-97 i've added support for video media in `0.1.1`

this was the flatten operation you were looking for https://github.com/lucidrains/flamingo-pytorch/blob/main/flamingo_pytorch/flamingo_palm.py#L306
